### ISSUE TITLE
Installation of php5-xmlrpc

### ISSUE THREAD

**Issue by niecw** [tejastank/openerp-php-connector#11]
In the index.php, you use the xmlrpc_get_type, which is available from PHP's XML-RPC library.  Unfortunately this library is not installed by default.  You might want to add a reminder in the README to install the library first.  In Ubuntu the command is:
```
sudo apt-get install php5-xmlrpc
```

**Comment by rkshakya** [comment]
Whats the exact cause and solution for this issue? I am using latest 3.0.1 version of XML-RPC lib but it does not fix the issue.
Thanks

**Comment by tejastank** [comment]
function xmlrpc_get_type($val)
  {
    switch(strtolower(gettype($val)))
    {
      case 'string':
        return $GLOBALS['xmlrpcString'];
      case 'integer':
      case 'resource':
        return $GLOBALS['xmlrpcInt'];
      case 'double':
        return $GLOBALS['xmlrpcDouble'];
      case 'boolean':
        return $GLOBALS['xmlrpcBoolean'];
      case 'array':
        $i = 0;
        $ok = true;
        foreach($val as $key => $value)
          if ($key !== $i)
          {
            $ok = false;
            break;
          }
          else
            $i++;

        return $ok ? $GLOBALS['xmlrpcArray'] : $GLOBALS['xmlrpcStruct'];
      case 'object':
        if (is_a($val, 'xmlrpcval'))
        {
          list($type, $val) = each($val->me);
          return str_replace(array('i4', 'dateTime.iso8601'), array('int', 'datetime'), $type);
        }
        return $GLOBALS['xmlrpcStruct'];
      case 'null':
        return $GLOBALS['xmlrpcBase64']; // go figure why...
    }
  }

**Comment by tejastank** [comment]
Download xmlrpc lib.

http://goo.gl/43OVxT

Which works great all time.

**Comment by rkshakya** [comment]
Hi Tejas. Thanks for the fixes :)
