### ISSUE TITLE
Operator handling in search and searchread domain

### ISSUE THREAD

**Issue by niecw** [tejastank/openerp-php-connector#12]
I think operators ('|', '&') are not handled in the search and searchread methods.  The foreach loop insist that each member should be an array with 3 members.

**Comment by shamandan** [comment]
If you want to use the OR operator, simply add the following in your searchread function :+1: 
$count = count($values)-1;
for($y=0; $y<$count; $y++) {
	$domains[] = new xmlrpcval( "|", "string" );
}

**Comment by tejastank** [comment]
Examples for search,

$rpc->searchread($uid, $pwd, array( array('partner_id', '=', (int)$partner_id) ), "sale.order", array('name','date_order','order_line', 'partner_id', 'partner_invoice_id','partner_shipping_id', 'amount_untaxed', 'amount_tax','amount_total'), 0, 1);


Default and condition :
$rpc->searchread($uid, $pwd, array( array('partner_id', '=', (int)$partner_id), array('partner_id', '=', (int)$partner_id) ), ...................

Other E.g: for or condition
$rpc->searchread($uid, $pwd, array('|',array('partner_id', '=', (int)$partner_id), array('partner_id', '=', (int)$partner_id) ), ...................


and condition
$rpc->searchread($uid, $pwd, array('&',array('partner_id', '=', (int)$partner_id), array('partner_id', '=', (int)$partner_id) ), ...................


I hope this will helps you. With this connector you can build your own new UI and own ERP.
Backend as odoo and front end as your own app.....

**Comment by damNor** [comment]
How can i search by many2one field . I want to search stock.quant model filter by product_id which is many2one field, please provide some example. Thanks
