### ISSUE TITLE
Search by many2one field

### ISSUE THREAD

**Issue by damNor** [tejastank/openerp-php-connector#14]
How can i search by many2one field . I want to search stock.quant model filter by product_id which is many2one field, please provide some example. Thanks

**Comment by tejastank** [comment]
Other E.g: for or condition
domain  =  array(,array('m2o_field_id', '=', (int)$partner_id) );

**Comment by damNor** [comment]
i've try that like this 

$data = $rpc->searchread( array( array('product_id', '=', '4109') ),"stock.quant");  
and still not working . Please help

**Comment by tejastank** [comment]
$data = $rpc->searchread( array( array('product_id', '=', 4109) ),"stock.quant");

 product_id (m2o) is actual integer not string,  '4109' is wrong

**Comment by damNor** [comment]
ok , i will try again. Thanks
